{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "generic-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecret.target.name }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy }}
  data:
    {{- range .Values.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ $.Values.global.projectName }}-{{ $.Values.global.environment }}/{{ $.Values.externalSecret.secretBasePath }}
        property: {{ .property }}
    {{- end }}
{{- end }}
