global:
  environment: dev

image:
  tag: "c02a641829d9b5779db43f42ea90ad45d6e50041"

ingress:
  annotations:
    alb.ingress.kubernetes.io/group.order: "10"
  hosts:
    - paths:
        - path: /dev
          pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

externalSecret:
  enabled: true
  data:
    - secretKey: EXAMPLE_SECRET
      property: example_secret
