global:
  environment: staging

image:
  tag: "edd9ec764c808710a0d5d3302c2bef9fbaad7437"

ingress:
  annotations:
    alb.ingress.kubernetes.io/group.order: "20"
  hosts:
    - paths:
        - path: /staging
          pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

externalSecret:
  enabled: true
  data:
    - secretKey: EXAMPLE_SECRET
      property: example_secret
