global:
  environment: staging

image:
  tag: "da0b70dfa5049db74ac74f19f30d502da23a50ee"

ingress:
  annotations:
    alb.ingress.kubernetes.io/group.order: "10"
  hosts:
    - paths:
        - path: /staging
          pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

externalSecret:
  enabled: true
  data:
    - secretKey: EXAMPLE_SECRET
      property: example_secret
