global:
  environment: prod

replicaCount: 3

image:
  tag: "prod-latest"

ingress:
  annotations:
    alb.ingress.kubernetes.io/group.order: "100"
  hosts:
    - paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

externalSecret:
  enabled: true
  data:
    - secretKey: EXAMPLE_SECRET
      property: example_secret
