global:
  environment: prod

replicaCount: 3

image:
  repository: 530424100135.dkr.ecr.eu-west-1.amazonaws.com/project-circle-nginx
  tag: "prod-latest"

ingress:
  hosts:
    - paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

externalSecret:
  enabled: true
  secretStore: aws-secrets-manager
  refreshInterval: 1h
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: EXAMPLE_SECRET
      remoteRef:
        key: project-circle-prod/app/config
        property: example_secret
