global:
  environment: staging

image:
  tag: "8b87ec12c12c8960a39d6fa12bfa376454b9b783"

ingress:
  annotations:
    alb.ingress.kubernetes.io/group.order: "20"
  hosts:
    - paths:
        - path: /staging
          pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

externalSecret:
  enabled: true
  data:
    - secretKey: EXAMPLE_SECRET
      property: example_secret
